[2025-05-14T02:53:07.535+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-14T02:53:07.570+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: diabetes_end_to_end.download_dataset scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T02:53:07.581+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: diabetes_end_to_end.download_dataset scheduled__2025-05-13T00:00:00+00:00 [queued]>
[2025-05-14T02:53:07.582+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-05-14T02:53:07.607+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): download_dataset> on 2025-05-13 00:00:00+00:00
[2025-05-14T02:53:07.620+0000] {standard_task_runner.py:63} INFO - Started process 257 to run task
[2025-05-14T02:53:07.624+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'diabetes_end_to_end', 'download_dataset', 'scheduled__2025-05-13T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp4k2hcuj7']
[2025-05-14T02:53:07.627+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask download_dataset
[2025-05-14T02:53:07.702+0000] {task_command.py:426} INFO - Running <TaskInstance: diabetes_end_to_end.download_dataset scheduled__2025-05-13T00:00:00+00:00 [running]> on host 55ce3247436c
[2025-05-14T02:53:07.843+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='diabetes_end_to_end' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-13T00:00:00+00:00'
[2025-05-14T02:53:07.845+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-14T02:53:07.887+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-14T02:53:07.888+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 20, in download_dataset
    os.makedirs("/data/raw", exist_ok=True)
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/data'
[2025-05-14T02:53:07.906+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=diabetes_end_to_end, task_id=download_dataset, execution_date=20250513T000000, start_date=20250514T025307, end_date=20250514T025307
[2025-05-14T02:53:07.923+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task download_dataset ([Errno 13] Permission denied: '/data'; 257)
[2025-05-14T02:53:07.960+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-14T02:53:07.993+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-14T02:53:07.998+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
